WebBanSua/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanSua.Models;

namespace WebBanSua.Controllers
{
    public class SanPhamController : Controller
    {
        private readonly CuaHangBanSuaContext _context;

        public SanPhamController(CuaHangBanSuaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaDmNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

       public async Task<IActionResult> SuaTT()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }

        public async Task<IActionResult> SuaChua()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }

        public async Task<IActionResult> BoPhomat()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }


        private bool SanPhamExists(int id)
        {
            return _context.SanPhams.Any(e => e.MaSp == id);
        }
    }
}

WebBanSua/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanSua.Models;

namespace WebBanSua.Controllers
{
    public class TinTucController : Controller
    {
        private readonly CuaHangBanSuaContext _context;

        public TinTucController(CuaHangBanSuaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.TinTucs.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.TinTucs
                .FirstOrDefaultAsync(m => m.MaTt == id);
            if (tinTuc == null)
            {
                return NotFound();
            }

            return View(tinTuc);
        }

       
    }
}

WebBanSua/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using WebBanSua.Extension
@using WebBanSua.ModelViews
 @{
    List<WebBanSua.ModelViews.CartItem> lisSP = new List<WebBanSua.ModelViews.CartItem>();
    var gio = Context.Session.Get<List<CartItem>>("GioHang");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
     <link rel="icon" type="image/png" href="~/img/logo.png">
    <title>Web Bán Sữa Dũng Phương</title>
    <link rel="stylesheet" href="~/lib/bootstrap-5.1.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/font/themify-icons-font/themify-icons/themify-icons.css">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/js/jquery/jquery-2.2.4.min.js" />
      <link rel="stylesheet" href="~/css/css_content.css">
    <style>
        .dangnhap-button a:hover {
            color: rgb(198, 209, 37);}

              .badge {
  padding-left: 9px;
  padding-right: 9px;
  -webkit-border-radius: 9px;
  -moz-border-radius: 9px;
  border-radius: 9px;
}

.label-warning[href],
.badge-warning[href] {
  background-color: #c67605;
}
#lblCartCount {
    font-size: 12px;
    background: #ff0000;
    color: #fff;
    padding: 0 5px;
    vertical-align: top;
    margin-left: -10px; 
}
    .giohang-header .cart {
        width: 40px;
        position: absolute;
        top: 25%;
        right: 30%;
    }

.giohang-header i{
    color: rgb(7, 44, 112);
}
    </style>
</head>
<body>
    <div class="main">
        <!-- Bắt đầu thanh menu navigation -->
        <div class="header" style="z-index: 10 !important;">
            <ul class="header-nav mb-0">
                <a asp-action="Index" asp-controller="Home"><img class="logo-header" src="~/img/logo.png" alt=""></a>
                <li><a asp-action="EditProfile" asp-controller="Home">GIỚI THIỆU</a>
                    <ul class="header-subnav">
                        <li><a href="">LỊCH SỬ</a></li>
                        <li><a href="">CHÍNH SÁCH & QUY ĐỊNH</a></li>
                    </ul>
                </li>
                <li><a asp-action="Index" asp-controller="SanPham">SẢN PHẨM</a></li>
                <li><a asp-action="Index" asp-controller="TinTuc">TIN TỨC</a>
                    <ul class="header-subnav">
                        <li><a href="">KHUYẾN MÃI</a></li>
                        <li><a href="">THÔNG TIN</a></li>
                    </ul>
                </li>
                <li><a href="">CỬA HÀNG</a></li>
                <li><a href="">HỖ TRỢ</a>
                    <ul class="header-subnav">
                        <li><a href="">DỊCH VỤ</a></li>
                        <li><a asp-action="Index" asp-controller="GioHang">LIÊN HỆ</a></li>
                        <li><a href="">BÁO CÁO</a></li>
                    </ul>
                </li>
            </ul>
             @* <a asp-action="Index" asp-controller="GioHang"><img class="cart" src="~/img/cart.png" alt=""></a>*@
            @if (Context.Session.GetString("MaKh") != null)
            {
            <div class="giohang-header" id="CartCount">
                <a asp-action="Index" asp-controller="GioHang"><img class="cart" src="~/img/cart.png" alt=""></a>
                @* @if(gio != null)
                {
               <a asp-action="Index" asp-controller="GioHang" >
                    <i class="fa" style="font-size:24px">&#xf07a;</i>
                    <span class='badge badge-warning' id='lblCartCount'> @gio.Count() </span>
                    </a>
                }
                else
                {
                     <a asp-action="Index" asp-controller="GioHang">
                    <i class="fa" style="font-size:24px">&#xf07a;</i>
                    <span class='badge badge-warning' id='lblCartCount'>0</span>
                    </a>
                }*@
            </div>
           
                 <div class="dangnhap-button">
                <a asp-action="UserDashboard" asp-controller="Home" style="text-decoration: none;"><i class="ti-user"></i> @Context.Session.GetString("TenKh").ToString()</a>
            </div>
            
            }
            else
            {
            <div class="dangnhap-button">
                <a asp-action="Login" asp-controller="Home" style="text-decoration:none;"><i class="ti-user"></i> Login</a>
            </div>
            }
            
        </div>
        
<!-- Thanh Slider và Button Tìm kiếm -->
        <div class="slider">
            <div id="header" class="search-btn">
                <input type="text" name="" placeholder="Tìm Kiếm" required id="" class="form-input-search">
                <a href=""><i id="search-btn" class="search-icon ti-search"></i></a>
             </div>
        </div>

        @RenderBody()

      <!-- Thẻ footer trên -->
        <div class="container-footer-top">
            <div class="logo-footer">
                <a asp-action="Index" asp-controller="Home"><img class="imglogo-footer" src="~/img/logo.png" alt=""></a>
            </div>
            <div class="row footer-top">
                <div class="col-md-4">
                    <ul class="footer-nav1">
                        <li><a href="">Liên hệ</a></li>
                        <li><a href="">Chăm sóc khách hàng</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="footer-nav2">
                        <li><a href="">Dịch vụ giao hàng tận nhà</a></li>
                        <li><a href="">Chính sách & Quy định chung</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                   <div class="pay-nav">
                       <p>Thanh toán</p>
                       <div class="row pay-imgnav">
                           <div class="col-sm-6"><img src="~/img/img-appstore.svg" alt=""></div>
                           <div class="col-sm-6"><img src="~/img/img-ch.svg" alt=""></div>
                       </div>
                </div>
            </div>
        </div>
        </div>

        <!-- Thẻ footer dưới -->
        <div class="footer-end">
            <div class="logo-info-brand">
                <a href=""><img class="yt-logo" width="10%" src="~/img/logo/yt-logo.png" alt=""></a>
                <a href=""><img class="fb-logo" width="10%" src="~/img/logo/fb-logo.png" alt=""></a>
                <a href=""><img class="ins-logo" width="10%" src="~/img/logo/ins-logo.png" alt=""></a>
                <a href=""><img class="swt-logo" width="10%" src="~/img/logo/swt-logo.png" alt=""></a>
            </div>
            <div class="footer-text-info">
                <p>Cơ quan chủ quản: Công ty Cổ phần Thực Phẩm Sạch Dũng Phương <br>
                Trụ sở: 01 Phố Xốm, Q. Hà Đông, TP. Hà Nội – Điện thoại: 1800555555 <br>
                MST: 2901270911 - Số ĐKKD: 2901270911 cấp ngày 06/09/2010 bởi Sở KH và ĐT thành phố Hà Nội.</p>
                 <a href="#search-btn" class="go-header"><i class='bx bxs-chevrons-up'></i></a>
        </div>
            </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <script type="text/javascript" src="~/js/slides.js"></script>
 <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script type="text/javascript">
           function AddToCartList(Id){
               $.ajax({
                   url: '/giohang/add-cart',
                   type: 'POST',
                   data:{ maSP: Id, soLuong: 1},
                  success: function(){
                         Swal.fire({
                        position: 'center',
                        icon: 'success',
                        title: 'Thêm thành công',
                        showConfirmButton: false,
                        timer: 1500
                        });
                        
                           },
                    error: function(){
                         Swal.fire({
                    icon: 'error',
                    title: 'Thất bại',
                    text: 'Đã có lỗi xảy ra',
                     showConfirmButton: false,
                        timer: 1500
                    });
                    }
               });

           }

           function loadHeader(){
                location.reload();
           }
       </script>
       <script type="text/javascript">
           function AddToCart(Id){
               $.ajax({
                   url: '/giohang/add-cart',
                   type: 'POST',
                   data:{ maSP: Id, soLuong: $('#txtsoLuong').val()},
                  success: function(data){
                         Swal.fire({
                        position: 'center',
                        icon: 'success',
                        title: 'Thêm thành công',
                        showConfirmButton: false,
                        timer: 1500
                        });
                           },
                    error: function(){
                         Swal.fire({
                    icon: 'error',
                    title: 'Thất bại',
                    text: 'Đã có lỗi xảy ra',
                     showConfirmButton: false,
                        timer: 1500
                    });
                    }
               });
           }
       </script>
  <script>
	$(document).ready(function(){
		$(".wish-icon i").click(function(){
			$(this).toggleClass("fa-heart fa-heart-o");
		});
	});	
</script>

       @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebBanSua/Views/Shared/_ProductLayout.cshtml
@using Microsoft.AspNetCore.Http
@using WebBanSua.Extension
@using WebBanSua.ModelViews
 @{
    List<WebBanSua.ModelViews.CartItem> lisSP = new List<WebBanSua.ModelViews.CartItem>();
    var gio = Context.Session.Get<List<CartItem>>("GioHang");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
     <link rel="icon" type="image/png" href="~/img/logo.png">
    <title>Web Bán Sữa Dũng Phương</title>
    <link rel="stylesheet" href="~/css/chitietsp.css">
    <link rel="stylesheet" href="~/lib/bootstrap-5.1.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/font/themify-icons-font/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/product-page.css" />
    <link rel="stylesheet" href="~/js/jquery/jquery-2.2.4.min.js" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
      <link rel="stylesheet" href="~/css/css_content.css">
    <style>
        .search-box{
    position: absolute;
    top: 26%;
    right: 12%;
    border-radius: 40px;
}
        .dangnhap-button a:hover {
            color: rgb(198, 209, 37);}

              .badge {
  padding-left: 9px;
  padding-right: 9px;
  -webkit-border-radius: 9px;
  -moz-border-radius: 9px;
  border-radius: 9px;
}

.label-warning[href],
.badge-warning[href] {
  background-color: #c67605;
}
#lblCartCount {
    font-size: 12px;
    background: #ff0000;
    color: #fff;
    padding: 0 5px;
    vertical-align: top;
    margin-left: -10px; 
}
    .giohang-header .cart {
        width: 40px;
        position: absolute;
        top: 25%;
        right: 30%;
    }
.giohang-header i{
    color: rgb(7, 44, 112);
}
    </style>
</head>
<body>
    <div class="main">
        <!-- Bắt đầu thanh menu navigation -->
        <div class="header" id="header-cart" style="z-index: 10 !important;">
            <ul class="header-nav mb-0">
                <a asp-action="Index" asp-controller="Home"><img class="logo-header" src="~/img/logo.png" alt=""></a>
                <li><a href="">GIỚI THIỆU</a>
                    <ul class="header-subnav">
                        <li><a href="">LỊCH SỬ</a></li>
                        <li><a href="">CHÍNH SÁCH & QUY ĐỊNH</a></li>
                    </ul>
                </li>
                <li><a asp-action="Index" asp-controller="SanPham">SẢN PHẨM</a></li>
                <li><a asp-action="Index" asp-controller="TinTuc">TIN TỨC</a>
                    <ul class="header-subnav">
                        <li><a href="">KHUYẾN MÃI</a></li>
                        <li><a href="">THÔNG TIN</a></li>
                    </ul>
                </li>
                <li><a href="">CỬA HÀNG</a></li>
                <li><a href="">HỖ TRỢ</a>
                    <ul class="header-subnav">
                        <li><a href="">DỊCH VỤ</a></li>
                        <li><a href="">LIÊN HỆ</a></li>
                        <li><a href="">BÁO CÁO</a></li>
                    </ul>
                </li>
            </ul>
            <div class="search-box">
                <input type="text" class="search-txt" placeholder="Tìm kiếm">
                <a href="" class="search-btn">
                    <i class='bx bx-search'></i>
                </a>
            </div>
           @if (Context.Session.GetString("MaKh") != null)
            {
            <div class="giohang-header" id="CartCount">
                <a asp-action="Index" asp-controller="GioHang"><img class="cart" src="~/img/cart.png" alt=""></a>
                @* @if(gio != null)
                {
               <a asp-action="Index" asp-controller="GioHang" >
                    <i class="fa" style="font-size:24px">&#xf07a;</i>
                    <span class='badge badge-warning' id='lblCartCount'> @gio.Count() </span>
                    </a>
                }
                else
                {
                     <a asp-action="Index" asp-controller="GioHang">
                    <i class="fa" style="font-size:24px">&#xf07a;</i>
                    <span class='badge badge-warning' id='lblCartCount'>0</span>
                    </a>
                }*@
            </div>
           
                 <div class="dangnhap-button">
                <a asp-action="UserDashboard" asp-controller="Home" style="text-decoration: none;"><i class="ti-user"></i> @Context.Session.GetString("TenKh").ToString()</a>
            </div>
            
            }
            else
            {
            <div class="dangnhap-button">
                <a asp-action="Login" asp-controller="Home" style="text-decoration:none;"><i class="ti-user"></i> Login</a>
            </div>
            }
        </div>

        <section class="content" style="margin-top:100px;">
        <div class="container-fluid">
             @RenderBody()
        </div>
    </section>

         <!-- Thẻ footer trên -->
        <div class="container-footer-top">
            <div class="logo-footer">
                <a href="index.html"><img class="imglogo-footer" src="~/img/logo.png" alt=""></a>
            </div>
            <div class="row footer-top">
                <div class="col-md-4">
                    <ul class="footer-nav1">
                        <li><a href="">Liên hệ</a></li>
                        <li><a href="">Chăm sóc khách hàng</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="footer-nav2">
                        <li><a href="">Dịch vụ giao hàng tận nhà</a></li>
                        <li><a href="">Chính sách & Quy định chung</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                   <div class="pay-nav">
                       <p>Thanh toán</p>
                       <div class="row pay-imgnav">
                           <div class="col-sm-6"><img src="~/img/img-appstore.svg" alt=""></div>
                           <div class="col-sm-6"><img src="~/img/img-ch.svg" alt=""></div>
                       </div>
                </div>
            </div>
        </div>
        </div>

        <!-- Thẻ footer dưới -->
        <div class="footer-end">
            <div class="logo-info-brand">
                <a href=""><img class="yt-logo" width="10%" src="~/img/logo/yt-logo.png" alt=""></a>
                <a href=""><img class="fb-logo" width="10%" src="~/img/logo/fb-logo.png" alt=""></a>
                <a href=""><img class="ins-logo" width="10%" src="~/img/logo/ins-logo.png" alt=""></a>
                <a href=""><img class="swt-logo" width="10%" src="~/img/logo/swt-logo.png" alt=""></a>
            </div>
            <div class="footer-text-info">
                <p>Cơ quan chủ quản: Công ty Cổ phần Thực Phẩm Sạch Dũng Phương <br>
                Trụ sở: 01 Phố Xốm, Q. Hà Đông, TP. Hà Nội – Điện thoại: 1800555555 <br>
                MST: 2901270911 - Số ĐKKD: 2901270911 cấp ngày 06/09/2010 bởi Sở KH và ĐT thành phố Hà Nội.</p>
                <a href="#header" class="go-header"><i class='bx bxs-chevrons-up'></i></a>
            </div>
        </div>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-latest.js"></script>
      <script type="text/javascript" src="~/js/slider-product.js"></script>
       <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
       <script type="text/javascript">
           function AddToCartList(Id){
               $.ajax({
                   url: '/giohang/add-cart',
                   type: 'POST',
                   data:{ maSP: Id, soLuong: 1},
                  success: function(){
                         Swal.fire({
                        position: 'center',
                        icon: 'success',
                        title: 'Thêm thành công',
                        showConfirmButton: false,
                        timer: 1500
                        });
                        
                           },
                    error: function(){
                         Swal.fire({
                    icon: 'error',
                    title: 'Thất bại',
                    text: 'Đã có lỗi xảy ra',
                     showConfirmButton: false,
                        timer: 1500
                    });
                    }
               });

           }

           function loadHeader(){
                $("#header-cart").reload();
           }
       </script>
 <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
       <script type="text/javascript">
           function AddToCart(Id){
               $.ajax({
                   url: '/giohang/add-cart',
                   type: 'POST',
                   data:{ maSP: Id, soLuong: $('#txtsoLuong').val()},
                  success: function(data){
                         Swal.fire({
                        position: 'center',
                        icon: 'success',
                        title: 'Thêm thành công',
                        showConfirmButton: false,
                        timer: 1500
                        });
                           },
                    error: function(){
                         Swal.fire({
                    icon: 'error',
                    title: 'Thất bại',
                    text: 'Đã có lỗi xảy ra',
                     showConfirmButton: false,
                        timer: 1500
                    });
                    }
               });
           }
       </script>
  <script>
	$(document).ready(function(){
		$(".wish-icon i").click(function(){
			$(this).toggleClass("fa-heart fa-heart-o");
		});
	});
    //$("#themvaogio").click(function(){
           
    //        var number =  $("#lblCartCount").text();
    //        number = parseInt(number) + 1;
    //         $("#lblCartCount").text(number);
    //         console.log(number);
            
    //    });
</script>
       @await RenderSectionAsync("Scripts", required: false)
</body>
</html>