WebBanSua/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanSua.Extension;
using WebBanSua.Models;
using WebBanSua.ModelViews;

namespace WebBanSua.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly CuaHangBanSuaContext _context;

        public CheckoutController(CuaHangBanSuaContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index(int id)
        {
            var maKH = HttpContext.Session.GetString("MaKh");
            id = int.Parse(maKH);
            var customerUser = await _context.KhachHangs.FindAsync(id);
            return View(customerUser);
        }

        [HttpPost]
        public IActionResult Index(KhachHang customer)
        {
            var cart = HttpContext.Session.Get<List<CartItem>>("GioHang");
            var tt = cart.Sum(t=>t.TongTien);
            var maKh = HttpContext.Session.GetString("MaKh");
            if (customer.Diachi == null)
            {
                ModelState.AddModelError("", "Địa chỉ không được để trống");
            }

            if (maKh != null)
            {
                var khachHang = _context.KhachHangs.AsNoTracking().SingleOrDefault(x => x.MaKh == Convert.ToInt32(maKh));
                khachHang.Phone = customer.Phone;
                khachHang.Diachi = customer.Diachi;
                _context.Update(khachHang);
                _context.SaveChanges();
            }
            if (ModelState.IsValid)
            {
                //Khởi tạo đơn hàng
                DonHang donHang = new DonHang();
                donHang.MaKh = customer.MaKh;
                donHang.NgayTao = DateTime.Now;
                donHang.TrangThaiHuyDon = true;
                donHang.ThanhToan = true;
                donHang.NgayThanhToan = DateTime.Now;
                donHang.Note = null;
                donHang.TongTien = Convert.ToInt32(tt);
                _context.Add(donHang);
                _context.SaveChanges();

                foreach (var item in cart)
                {
                    ChiTietDonHang chiTietDonHang = new ChiTietDonHang();
                    chiTietDonHang.MaDh = donHang.MaDh;
                    chiTietDonHang.MaSp = item.sanPham.MaSp;
                    chiTietDonHang.SoLuong = item.soLuong;
                    chiTietDonHang.TongTien = Convert.ToInt32(item.TongTien);
                    chiTietDonHang.Ngaygiao = 0;
                    _context.Add(chiTietDonHang);


                    var sanPham = _context.SanPhams.AsNoTracking().SingleOrDefault(x => x.MaSp == item.sanPham.MaSp);
                    sanPham.SoLuong = sanPham.SoLuong - item.soLuong;
                    _context.Update(sanPham);
                }
                _context.SaveChanges();
                HttpContext.Session.Remove("GioHang");
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            return View();

        }
    }
}

WebBanSua/Controllers/GioHangController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using WebBanSua.Extension;
using WebBanSua.Models;
using WebBanSua.ModelViews;

namespace WebBanSua.Controllers
{
    public class GioHangController : Controller
    {
        private readonly CuaHangBanSuaContext _context;

        public GioHangController(CuaHangBanSuaContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var listGio = GioHang;
            return View(GioHang);
        }
        public List<CartItem> GioHang
        {
            get
            {
                var gh = HttpContext.Session.Get<List<CartItem>>("GioHang");
                if (gh == default(List<CartItem>))
                {
                    gh = new List<CartItem>();
                }
                return gh;
            }
        }

        [HttpPost]
        [Route("/giohang/add-cart")]
        public IActionResult AddToCart(int maSP, int soLuong)
        {
            List<CartItem> gioHang = GioHang;
            try
            {
                //Thêm vào giỏ
                CartItem item = gioHang.SingleOrDefault(p => p.sanPham.MaSp == maSP);
                if (item != null)
                {
                    item.soLuong = item.soLuong + soLuong;

                    HttpContext.Session.Set<List<CartItem>>("GioHang", gioHang);
                }
                else
                {
                    SanPham sp = _context.SanPhams.SingleOrDefault(p => p.MaSp == maSP);
                    item = new CartItem
                    {
                        soLuong = soLuong,
                        sanPham = sp
                    };
                    gioHang.Add(item);
                }
                HttpContext.Session.Set<List<CartItem>>("GioHang", gioHang);

                return Json(new { succeess = true });

            }
            catch (Exception ex)
            {
                return Json(new { succeess = false });
            }

        }

        [HttpPost]
        [Route("/giohang/update-cart")]
        public IActionResult UpdateCart(int maSP, int soLuong)
        {
           var gioHang = HttpContext.Session.Get<List<CartItem>>("GioHang");
            try
            {

               if(gioHang != null)
                {
                    CartItem item = gioHang.SingleOrDefault(p => p.sanPham.MaSp == maSP);
                    if (item != null)
                    {
                        item.soLuong = soLuong;
                    }
                    HttpContext.Session.Set<List<CartItem>>("GioHang", gioHang);
                }
                return Json(new
                {
                    soLuong = GioHang.Sum(p => p.soLuong)
                });

            }
            catch (Exception ex)
            {
                return Json(new { succeess = false });
            }

        }

        [HttpPost]
        [Route("/giohang/remove")]
        public ActionResult Remove(int maSP)
        {
            try
            {
                List<CartItem> gioHang = GioHang;
                CartItem item = gioHang.SingleOrDefault(p => p.sanPham.MaSp == maSP);
                if (item != null)
                {
                    gioHang.Remove(item);
                }
                HttpContext.Session.Set<List<CartItem>>("GioHang", gioHang);
                return Json(new { succeess = true });
            }
            catch
            {
                return Json(new { succeess = false });
            }

        }

        public ActionResult CleanCart()
        {
            HttpContext.Session.Remove("GioHang");
            return RedirectToAction("Index");

        }

       
    }
}

WebBanSua/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanSua.Models;

namespace WebBanSua.Controllers
{
    public class SanPhamController : Controller
    {
        private readonly CuaHangBanSuaContext _context;

        public SanPhamController(CuaHangBanSuaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaDmNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

       public async Task<IActionResult> SuaTT()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }

        public async Task<IActionResult> SuaChua()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }

        public async Task<IActionResult> BoPhomat()
        {
            var cuaHangBanSuaContext = _context.SanPhams.Include(s => s.MaDmNavigation);
            return View(await cuaHangBanSuaContext.ToListAsync());
        }


        private bool SanPhamExists(int id)
        {
            return _context.SanPhams.Any(e => e.MaSp == id);
        }
    }
}

WebBanSua/Views/GioHang/Index.cshtml
@using Microsoft.AspNetCore.Http
@model List<WebBanSua.ModelViews.CartItem>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ProductLayout.cshtml";
}


<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="~/css/cart.css" />
<div class="container padding-bottom-3x mb-1">
    <!-- Shopping Cart-->
    @if(Model != null && Model.Count()>0)
        {
                <div class="table-responsive shopping-cart">
        
        <table class="table">
            <thead>
                <tr>
                    <th>Tên Sản Phẩm</th>
                    <th class="text-center">Số Lượng</th>
                    <th class="text-center">Đơn Giá</th>
                    <th class="text-center">Giảm Giá (Nếu có)</th>
                    <th class="text-center"><a class="btn btn-sm btn-outline-danger" asp-action="CleanCart" asp-controller="GioHang">Xóa tất cả</a></th>
                </tr>
            </thead>
            <tbody>
                    @foreach (var item in Model)
                    {
                         <tr>
                    <td>
                        <div class="product-item">
                            <a class="product-thumb" asp-action="Details" asp-route-id="@item.sanPham.MaSp"><img src="@item.sanPham.AnhSp" alt="Product"></a>
                            <div class="product-info">
                                 
                                <h4 class="product-title"><a asp-action="Details" asp-route-id="@item.sanPham.MaSp">@item.sanPham.TenSp</a></h4><span><em>Size:</em> 108ml</span>
                            </div>
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="count-input">
                           <label for="txtsoLuong">Số Lượng:</label>
                           <input onclick="UpdateCart(@item.sanPham.MaSp)" id="txtsoLuong" name="txtsoLuong" max="100" step="1" value="@item.soLuong" type="number" style="width:80px; text-align:center; margin-left:8px;"/>
                        </div>
                    </td>
                    <td class="text-center text-lg text-medium">@item.TongTien.ToString("#,##0") VNĐ</td>
                    <td class="text-center text-lg text-medium">0</td>
                    <td class="text-center"><a href="" class="remove-from-cart" data-toggle="tooltip" title="" data-original-title="Remove item" onclick="RemoveCart(@item.sanPham.MaSp)" ><i class="fa fa-trash"></i></a></td>
                </tr>
                    }
            </tbody>
        </table>
    </div>
    <div class="shopping-cart-footer">
        <div class="column">
            <form class="coupon-form" method="post">
                <input class="form-control form-control-sm" type="text" placeholder="Mã giảm giá" required="">
                <button class="btn btn-outline-primary btn-sm" type="submit">Áp dụng</button>
            </form>
        </div>
        <div class="column text-lg">Tổng tiền: <span class="text-medium">@Model.Sum(x=> x.TongTien).ToString("#,##0") VNĐ</span></div>
    </div>
        }
        else
        {
            <h3 style="margin-top:100px !important;">Giỏ Hàng Của Bạn Đang Trống</h3>
        }

    <div class="shopping-cart-footer">
        <div class="column"><a class="btn btn-outline-secondary" asp-action="Index" asp-controller="SanPham"><i class="icon-arrow-left"></i>&nbsp;Quay Lại Mua Thêm</a></div>
        
            <div class="column"><a class="btn btn-success" asp-action="Index" asp-controller="Checkout">Mua Hàng</a></div>
       
    </div>
</div>


 <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
       <script type="text/javascript">
           function RemoveCart(Id){
              $.ajax({
                   url: '/giohang/remove',
                   type: 'POST',
                   data:{ maSP: Id},
                  success: function(data){ 
                         console.log(data);
                         location.reload();
                           },
                    error: function(){
                         Swal.fire({
                    icon: 'error',
                    title: 'Thất bại',
                    text: 'Đã có lỗi xảy ra',
                     showConfirmButton: false,
                        timer: 1500
                    });
                    }
               });
           }

           function UpdateCart(Id){
              $.ajax({
                   url: '/giohang/update-cart',
                   type: 'POST',
                   data:{ maSP: Id, soLuong: $('#txtsoLuong').val()},
                  success: function(data){ 
                         console.log(data);
                         location.reload();
                           },
                    error: function(){
                         Swal.fire({
                    icon: 'error',
                    title: 'Thất bại',
                    text: 'Đã có lỗi xảy ra',
                     showConfirmButton: false,
                        timer: 1500
                    });
                    }
               });
           }
       </script>